topicswords = {
  "Computer Science": [
    "algorithms", "programming", "data structures", "software engineering",
    "operating systems", "artificial intelligence", "computer networks",
    "cybersecurity", "machine learning", "web development",
    "database management", "parallel computing", "cryptography",
    "information theory", "computer graphics", "image processing",
    "computer vision", "natural language processing", "programming languages",
    "computer architecture", "computer organization", "data compression",
    "data encryption", "distributed systems", "file systems",
    "human-computer interaction", "multi-agent systems",
    "operating system design", "real-time systems", "robotics",
    "security engineering", "signal processing", "virtual reality",
    "cloud computing", "network security", "web design",
    "mobile application development", "cybercrime", "digital forensics",
    "algorithmic game theory", "formal methods", "graph theory",
    "computational geometry", "bioinformatics", "neural networks",
    "genetic algorithms", "fuzzy logic", "expert systems", "decision trees",
    "machine vision", "intelligent agents", "semantic web",
    "information retrieval", "speech recognition", "image recognition",
    "database systems", "big data", "data mining", "knowledge representation",
    "logic programming", "software testing", "usability engineering",
    "design patterns", "agile software development",
    "object-oriented programming", "functional programming",
    "aspect-oriented programming", "service-oriented architecture",
    "client-server computing", "grid computing", "high-performance computing",
    "distributed computing", "peer-to-peer computing", "concurrent computing",
    "real-time computing", "embedded systems", "computer vision"
  ],
  "Physics": [
    "mechanics", "thermodynamics", "electromagnetism", "optics", "waves",
    "quantum mechanics", "relativity", "astrophysics", "nuclear physics",
    "particle physics", "atomic physics", "condensed matter physics",
    "solid state physics", "plasma physics", "statistical mechanics",
    "cosmology", "gravitation", "black holes", "string theory",
    "supersymmetry", "quantum field theory", "molecular physics", "biophysics",
    "materials science", "acoustics", "fluid mechanics", "geophysics",
    "mechanical engineering", "electrical engineering", "civil engineering",
    "chemical engineering", "biomedical engineering", "systems engineering",
    "astronomy", "astrophotography", "optical astronomy", "radio astronomy",
    "observational astronomy", "celestial mechanics", "space physics",
    "theoretical physics", "experimental physics", "applied physics",
    "mathematical physics", "classical mechanics", "quantum optics",
    "atomic spectroscopy", "neutron scattering", "x-ray diffraction",
    "quantum computing", "information theory", "energy storage",
    "semiconductor physics", "optoelectronics", "nanotechnology",
    "energy conversion", "fusion power", "laser physics",
    "high energy physics", "medical physics", "environmental physics",
    "neurophysics", "time crystals", "spintronics", "quantum materials",
    "optical tweezers", "quantum sensing", "spin qubits",
    "optical coherence tomography", "quantum communication"
  ],
  "Chemistry": [
    "atomic structure", "chemical bonding", "stoichiometry", "thermochemistry",
    "electrochemistry", "acid-base chemistry", "organic chemistry",
    "inorganic chemistry", "analytical chemistry", "biochemistry",
    "physical chemistry", "quantum chemistry", "molecular biology",
    "spectroscopy", "photochemistry", "polymer chemistry", "colloid chemistry",
    "supramolecular chemistry", "material chemistry", "geochemistry",
    "atmospheric chemistry", "environmental chemistry", "forensic chemistry",
    "pharmaceutical chemistry", "green chemistry", "food chemistry",
    "surface chemistry", "petrochemistry", "industrial chemistry",
    "coordination chemistry", "medicinal chemistry", "synthetic chemistry",
    "crystallography", "solid-state chemistry", "thermodynamics", "catalysis",
    "biomaterials", "nanomaterials", "crystal engineering", "microfluidics",
    "lab-on-a-chip", "membrane technology", "supercritical fluids",
    "electrolysis", "chromatography", "mass spectrometry", "NMR spectroscopy",
    "IR spectroscopy", "UV-Vis spectroscopy", "fluorescence spectroscopy",
    "Raman spectroscopy", "X-ray crystallography", "titration",
    "gravimetric analysis", "spectrophotometry",
    "atomic absorption spectroscopy", "gas chromatography",
    "liquid chromatography", "paper chromatography",
    "ion exchange chromatography", "size exclusion chromatography",
    "electrophoresis", "NMR imaging", "polarimetry", "electrogravimetry",
    "potentiometry", "amperometry", "conductometry", "viscometry", "osmometry",
    "calorimetry", "coulometry", "chemical kinetics", "photoelectrochemistry",
    "quantum dots", "surface-enhanced Raman spectroscopy",
    "computational chemistry", "metabolomics", "bioanalytical chemistry",
    "cheminformatics", "heterogeneous catalysis", "homogeneous catalysis",
    "zeolites", "solvothermal synthesis", "nanoparticles", "micelles",
    "emulsions", "colloids", "zeolites", "desalination", "water purification",
    "wastewater treatment", "air pollution", "soil chemistry",
    "pesticide chemistry", "chemical thermodynamics", "bioinorganic chemistry",
    "bioorganic chemistry", "green synthesis", "glycochemistry",
    "organometallic chemistry", "radiochemistry", "actinide chemistry",
    "lanthanide chemistry", "petrochemicals", "aromatic chemistry",
    "aliphatic chemistry", "inorganic synthesis", "physical organic chemistry",
    "asymmetric synthesis", "enantioselective catalysis",
    "metal-organic frameworks", "pharmaceutical analysis", "toxicology",
    "pharmacokinetics", "pharmacodynamics", "drug design", "drug delivery",
    "molecular modeling", "protein chemistry", "enzymology",
    "carbohydrate chemistry", "lipid chemistry", "natural products chemistry",
    "food analysis", "food additives", "flavor chemistry",
    "fragrance chemistry", "cosmetics chemistry", "dye chemistry",
    "pigment chemistry", "ink chemistry", "coatings chemistry",
    "lubricant chemistry", "textile chemistry", "paper chemistry",
    "agrochemistry"
  ],
  "Biology": [
    "synthetic biology", "metagenomics", "structural biology", "phylogenetics",
    "epigenetics", "microbial ecology", "genetic engineering", "gene therapy",
    "stem cell research", "cancer biology", "neurobiology",
    "behavioral genetics", "population genetics",
    "evolutionary developmental biology", "computational biology",
    "immunotherapy", "biological imaging", "biological control",
    "biological invasion", "biomarkers", "biological rhythms",
    "bioluminescence", "bioreactors", "biogeochemistry", "biogeography",
    "biological oceanography", "biological wastewater treatment",
    "biological nitrogen removal", "biological phosphorus removal",
    "biological hydrogen production", "biological desulfurization",
    "biological denitrification", "biological nutrient removal",
    "biological waste gas treatment", "biological soil improvement",
    "biological pest control", "biological weed control",
    "biological fertilizer", "biological insecticide", "biological herbicide",
    "biological fungicide", "biological nematicide", "biological pesticide",
    "biological insect repellent", "biological molluscicide",
    "biological miticide", "biological virucide", "biological antimicrobial",
    "biological disinfectant", "biological sanitizer",
    "biological preservative", "biological control agent",
    "biological additive", "biological product", "biological soil amendment",
    "biological filter", "biological reactor", "biological detoxification",
    "biological remediation", "biological restoration", "biological diversity",
    "biological monitoring", "biological assessment", "biological evaluation",
    "biological risk assessment", "biological assay", "biological marker",
    "biological response modifier", "biological specimen",
    "biological conservation", "biological restoration",
    "biological management", "biological survey",
    "biological impact assessment", "biological indicator",
    "biological reserve", "biological hotspot", "biological corridor",
    "biological invasion assessment", "biological resource management",
    "biological sampling", "biological census", "biological modeling",
    "biological forecasting", "biological planning",
    "biological risk management", "biological emergency response",
    "biological threat assessment", "biological security", "biological safety"
  ],
  "General": [
    "CAS", "Extended Essay", "Theory of Knowledge", "Internal Assessment",
    "External Assessment", "IB Diploma Programme", "IB Learner Profile",
    "Global Contexts", "Approaches to Learning", "Subject Guides",
    "Assessment Criteria", "Criterion-Referenced Assessment",
    "Holistic Assessment", "Summative Assessment", "Formative Assessment",
    "Higher Level", "Standard Level", "Core", "Elective", "Option",
    "Bilingual Diploma", "IBCC", "Recognition Policy", "Grade Boundaries",
    "Academic Honesty", "Plagiarism", "Collaborative Learning",
    "International Mindedness", "Interdisciplinary Learning",
    "Inquiry-Based Learning", "Student-Centered Learning",
    "Teacher Support Material", "Transdisciplinary Skills", "Personal Project"
  ]
}
